wsgi/bookncart/bookncart/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('', include('bookncart_web.urls', namespace='bookncart_web')),
    url(r'^app/', include('bookncart_app.urls', namespace='bookncart_app')),
    url(r'^admin/', include(admin.site.urls)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wsgi/bookncart/bookncart_web/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/(?P<book_id>[0-9]+)/$', views.book_detail, name='book_detail'),
    url(r'^add_to_cart/', views.add_to_cart, name='add_to_cart'),
    url(r'^delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    url(r'^facebook_login/', views.facebook_login, name='facebook_login'),
    url(r'^google_login/', views.google_login, name='google_login'),
    url(r'^sign_out/', views.sign_out, name='sign_out'),
]

wsgi/bookncart/bookncart_web/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpRequest, Http404, JsonResponse
from django.shortcuts import render, redirect
from PIL import Image
from django.template import RequestContext
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.core import serializers
import json
import requests
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from bookncart_web.models import *


def index(request):
    # try:
    # del request.session['cart_items']
    best_selling_books = Books.objects.filter(stock__gt=0).order_by('-sell_count')[:30]
    top_rated_books = Books.objects.filter(stock__gt=0).order_by('-view_count')[:30]
    featured_books = Books.objects.filter(stock__gt=0).filter(is_featured__exact=1).order_by('-view_count')[:30]
    new_added_books = Books.objects.filter(stock__gt=0).order_by('-upload_date')[:30]
    context = RequestContext(request, {
        'best_selling_books': best_selling_books,
        'top_rated_books': top_rated_books,
        'featured_books': featured_books,
        'new_added_books': new_added_books
    }, [view_for_requestcontext_data_common_view])
    return render(request, 'bookncart_web/index.html', context)
    # except:
    #     raise Http404('Internal error occurred in index view')


def book_detail(request, book_id):
    try:
        book = get_object_or_404(Books, pk=book_id)
        book.view_count += 1
        book.save()
        related_books = []
        tags = book.tags_id.all()
        for tag in tags:
            temp_books = tag.books_set.all()
            for temp_book in temp_books:
                if temp_book.id != book.id and temp_book.stock > 0:
                    related_books.append(temp_book)
        related_books = set(related_books)
        reviews = Reviews.objects.filter(book_id__exact=book_id).filter(is_approved__exact=1).order_by('-timestamp')

        context = RequestContext(request, {
            'book': book,
            'related_books': related_books,
            'reviews': reviews
        }, [view_for_requestcontext_data_common_view])
        return render(request, 'bookncart_web/book_detail.html', context)
    except:
        raise Http404('Internal error occurred in book_detail view')


def add_to_favourites(request):
    # if request
    pass


@csrf_exempt
def delete_from_cart(request):
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        book_cart = get_object_or_404(Books, pk=book_id)
        try:
            new_cart_items = []
            cart_items = request.session['cart_items']
            for cart_item in cart_items:
                if cart_item['id'] == book_cart.id:
                    pass
                else:
                    new_cart_items.append(cart_item)

            request.session['cart_items'] = new_cart_items

            cart_items = new_cart_items
            subtotal = 0
            quantity = 0
            for cart_item in cart_items:
                subtotal += cart_item['amount']
                quantity += cart_item['quantity']
            total = subtotal + 50
            if subtotal == 0:
                total = 0

            request.session['cart_subtotal'] = subtotal
            request.session['cart_total'] = total
            request.session['cart_quantity'] = quantity

            return JsonResponse({'cart_items': cart_items, 'subtotal': subtotal, 'quantity': quantity, 'total': total,
                                 'message_type': 'delete'})
        except:
            return Http404


@csrf_exempt
def add_to_cart(request):
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        book_cart = get_object_or_404(Books, pk=book_id)
        cart_items = []
        error_message = None
        try:
            cart_items = request.session['cart_items']
        except:
            cart_items = []
        if len(cart_items) > 0:
            found = False
            for cart_item in cart_items:
                if cart_item['id'] == book_cart.id:
                    if cart_item['quantity'] < 10:
                        cart_item['quantity'] += 1
                        cart_item['amount'] = cart_item['price'] * cart_item['quantity']
                    else:
                        error_message = "You cannot add more than 10 items of " + book_cart.name;
                    found = True
            if found == False:
                cart_items.append(
                    {'name': book_cart.name, 'id': book_cart.id, 'price': book_cart.price, 'quantity': 1,
                     'image_url': book_cart.image_url.url, 'amount': book_cart.price})
        else:
            cart_items.append(
                {'name': book_cart.name, 'id': book_cart.id, 'price': book_cart.price, 'quantity': 1,
                 'image_url': book_cart.image_url.url, 'amount': book_cart.price})

        request.session['cart_items'] = cart_items

        subtotal = 0
        quantity = 0
        for cart_item in cart_items:
            subtotal += cart_item['amount']
            quantity += cart_item['quantity']
        total = subtotal + 50

        request.session['cart_subtotal'] = subtotal
        request.session['cart_total'] = total
        request.session['cart_quantity'] = quantity

        return JsonResponse({'cart_items': cart_items, 'subtotal': subtotal, 'quantity': quantity, 'total': total,
                             'error_message': error_message, 'message_type': 'add'})


def view_for_requestcontext_data_common_view(request):
    top_category = Categories.objects.filter(is_root__exact=1)
    sub_category = Categories.objects.filter(is_root__exact=0).filter(is_last__exact=0)
    subsub_category = Categories.objects.filter(is_last__exact=1)
    cart_items = []
    cart_subtotal = 0
    cart_total = 0
    cart_quantity = 0
    try:
        cart_items = request.session['cart_items']
        cart_subtotal = request.session['cart_subtotal']
        cart_total = request.session['cart_total']
        cart_quantity = request.session['cart_quantity']
    except:
        cart_items = []
    context = {'top_category': top_category,
               'sub_category': sub_category,
               'subsub_category': subsub_category,
               'cart_items': cart_items,
               'cart_total': cart_total,
               'cart_subtotal': cart_subtotal,
               'cart_quantity': cart_quantity}
    return context


@csrf_exempt
def google_login(request):
    if request.method == 'POST':
        access_token = request.POST.get('access_token')
        expires_in = request.POST.get('expires_in')
        granted_scopes = request.POST.get('scope')
        email = request.POST.get('email')
        name = request.POST.get('name')
        image_url = request.POST.get('image')
        google_id_token = request.POST.get('id_token')
        user_id = request.POST.get('google_id')
        profile_object = request.POST.get('json_profile_object')

        username = str(email) + str(user_id)
        password = user_id
        if len(username) > 30:
            username = username[0:29]

        user_profile = None
        user = authenticate(username=username, password=password)
        if user is not None:
            user_profile = UserProfiles.objects.get(user_link_obj=user)
            user_profile.access_token = access_token
            user_profile.access_token_expires_in = expires_in
            user_profile.granted_scopes = str(granted_scopes)
            user_profile.profile_details_json_object = profile_object
            user_profile.profile_image = image_url
            if google_id_token is not None:
                user_profile.google_id_token = google_id_token
            user_profile.login_count += 1
            user_profile.is_logged_in = True
            user_profile.save()
            login(request, user)
        else:
            user = User.objects.create_user(username, str(email), password)
            user.first_name = name
            user.save()
            user_profile = UserProfiles(user_link_obj=user)
            user_profile.full_name = name
            user_profile.first_name = name
            user_profile.email = email
            user_profile.password = password
            user_profile.username = username
            user_profile.userIDAuth = user_id
            user_profile.is_google_account = True
            user_profile.access_token = access_token
            user_profile.access_token_expires_in = expires_in
            user_profile.google_id_token = google_id_token
            user_profile.granted_scopes = str(granted_scopes)
            user_profile.profile_details_json_object = profile_object
            user_profile.profile_image = image_url
            user_profile.login_count = 1
            user_profile.is_logged_in = True
            user_profile.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
        if user_profile is not None:
            location = Location(user_id=user_profile)
            location.http_get_host = request.get_host()
            location.http_host = request.META['HTTP_HOST']
            location.http_referer = request.META['HTTP_REFERER']
            location.http_user_agent = request.META['HTTP_USER_AGENT']
            try:
                location.remote_host = request.META['REMOTE_ADDR']
                location.remote_addr = request.META['REMOTE_HOST']
            except:
                pass
            try:
                location.remote_user = request.META['REMOTE_USER']
            except:
                pass
            location.save()
        return HttpResponse()


@csrf_exempt
def facebook_login(request):
    if request.method == 'POST':
        access_token = request.POST.get('access_token')
        expires_in = request.POST.get('expires_in')

wsgi/bookncart/bookncart_web/templates/bookncart_web/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% extends "bookncart_web/base.html" %}
	{% load staticfiles %}
	{% block css_block %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BooksCart</title>
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/bootstrap/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/slick/slick.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/slick/slick-theme.css' %}"/>

	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/navBarCss.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/wishlistCss.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/cartCSS.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/modalCss.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/categoryNav.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/css/footerCss.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/subpages/css/logo_container_css.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/bootstrap_rating_bar/star-rating.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/subpages/product/css/productCss.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'bookncart_web/subpages/product/css/review.css' %}">
	{% endblock css_block %}
</head>
<body>

	{% block content_block %}
	<div id="up_button_floating"><span class="glyphicon glyphicon-chevron-up" id="up_button_floating_glyph"></span></div>

	<div class="margin_top_for_nav"></div>

	<div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'bookncart_web/img_site/holy-book-2560x16001.jpg' %}">
		<div class="navbar_home">
			<a href="#"><img src="{% static 'bookncart_web/img_site/logo.png' %}" class="logo_image"></a>			
		</div>
	</div>

	<div class="container" style="margin-top : 30px">

		<div class="row">
			<div class="col-sm-2"></div>
			<div class="col-sm-3">
				<div class="description_image_div">
					<img src="{{ book.image_url.url }}" class="description_image img-responsive" alt="">
				</div>
			</div>
			<div class="col-sm-5">
				<h3>{{ book.name }}</h3> 
				<hr>                  
				<p><mark>Availability : In Stock</mark></p>                       
				<h3>Price : <del class="text-danger">Rs. {{ book.mrp }}</del> Rs. {{ book.price }}</h3>
				<p class="text-muted">Inclusive of all taxes. Free home delivery.</p>

				<div class="quantity_button_group">
					<p>
						<div class="input-group">
							<span class="input-group-btn">
								<button type="button" class="btn btn-default btn-number" disabled="disabled" data-type="minus" data-field="quant[1]">
									<span class="glyphicon glyphicon-minus"></span>
								</button>	
							</span>
							<input type="text" readonly="readonly" name="quant[1]" class="form-control input-number" value="1" min="1" max="10">
							<span class="input-group-btn">
								<button type="button" class="btn btn-default btn-number" data-type="plus" data-field="quant[1]">
									<span class="glyphicon glyphicon-plus"></span>
								</button>
							</span>
						</div>
					</p>
				</div>	
				<button type="button" class="btn btn-info">Buy Now</button>
				<br>
				<div class="cart_wishlist_buttons">
					<button type="button" class="btn btn-success">Add to Cart</button>
					<button type="button" class="btn btn-danger">Add to Wishlist</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12" role="tabpanel">
				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active">
						<a id="tab1" aria-controls="description" role="tab" data-toggle="tab" href="#description">Description</a>
					</li>
					<li role="presentation">
						<a id="tab2" aria-controls="specification" role="tab" data-toggle="tab" href="#specification">Specification</a>
					</li>
					<li role="presentation">
						<a id="tab3" aria-controls="reviews" role="tab" data-toggle="tab" href="#reviews">Reviews</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane active fade in" role="tabpanel" id="description">
						{{ book.description }}
					</div>
					<div class="tab-pane fade" role="tabpanel" id="specification">
						<table class="table table-striped table-bordered">
							<tr>
								<th colspan="2">Book Details</th>
							</tr>
							<tr>
								<td class="detail_name">Author</td>
								<td>{{ book.author }}</td>
							</tr>
							<tr>
								<td class="detail_name">Publisher</td>
								<td>{{ book.publisher }}</td>
							</tr>
							<tr>
								<td class="detail_name">Condition</td>
								<td>{% if book.condition_is_old %}Old{% else %}New{% endif %}
								</td>
							</tr>   
							<tr>
								<td class="detail_name">ISBN</td>
								<td>{{ book.isbn }}</td>
							</tr>
							<tr>
								<td class="detail_name">Binding</td>
								<td>{{ book.binding }}</td>
							</tr>
							<tr>
								<td class="detail_name">Edition</td>
								<td>{{ book.edition }}</td>
							</tr>
							<tr>
								<td class="detail_name">Number of Pages</td>
								<td>{{ book.number_of_pages }}</td>
							</tr>
							<tr>
								<td class="detail_name">Language</td>
								<td>{{ book.language }}</td>
							</tr>
							<tr>
								<td class="detail_name">Publication Year</td>
								<td>{{ book.publication_year }}</td>
							</tr>
						</table>
					</div>
					<div class="tab-pane fade" role="tabpanel" id="reviews">
						<div class="new_review_container">
							<div id="write_review_line"><img src="{% static 'bookncart_web/img_site/write review.png' %}" width="20px"/> &nbsp;&nbsp;Write a review</div>
							<div id="write_new_review_div" style="display: none">
								<hr>
								<form class="form-horizontal">
									<div class="form-group">
										<label for="inputname3" class="col-sm-1 control-label">Name</label>
										<div class="col-sm-8">
											<input type="text" class="form-control" id="inputname3" placeholder="Name">
										</div>
									</div>
									<div class="form-group">
										<label for="inputEmail3" class="col-sm-1 control-label">Email</label>
										<div class="col-sm-8">
											<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
										</div>
									</div>
									<div class="form-group">
										<label for="" class="col-sm-1 control-label">Rating</label>
										<div class="col-sm-8">
											<input id="input-new" class="rating" data-min="0" data-max="5" data-step="1" data-size="sm" data-show-clear="false" data-show-caption="false">                                
										</div>
									</div>
									<div class="form-group">
										<label for="" class="col-sm-1 control-label">Review</label>
										<div class="col-sm-8">
											<textarea class="form-control" rows="3"></textarea>                     
										</div>
									</div>
								</form>
							</div>
						</div>

						<div style="margin-top: 20px;" ></div>

						{% for review in reviews %}
						<div class="review_old_reviews">
							Review By : {% if review.user_id %}{{ review.user_id.name }}
							{% else %}{{ review.name }}{% endif %}
							<input id="input-1" value="{{ review.rating }}" class="rating" data-min="0" data-max="5" data-step="1" data-readonly="true" data-size="xs" data-show-clear="false" data-show-caption="false">
						</input>
						<div>{{ review.comment }}</div>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
	</div>
	<hr>
</div>

<div class="container">
	<p class="heading_category">Related Books</p>
</div>

<div class="container show_products_as_slick">
	{% for related_book in related_books %}
	<div class="product_div">
		<div class="product_image_div">
			<a href="{% url 'bookncart_web:book_detail' related_book.id %}"><img src="{{ related_book.image_url.url }}" class="product_image_img" ></a>
		</div>
		<div class="product_name"><a href="{% url 'bookncart_web:book_detail' related_book.id %}">{{ related_book.name }}</a></div>
		<div class="product_price">Rs. {{ related_book.price }}</div>
		<div class="buttons_group">
			<div class="button_cart">
				<span class="glyphicon glyphicon-shopping-cart glyphicon_product_css" ></span>
				<span class="small_text_cart">ADD TO CART</span>
			</div>
			<div class="button_favourite">

				<span class="glyphicon glyphicon glyphicon-heart glyphicon_product_css_heart" ></span>
			</div>
			<div class="button_compare">
				<span class="glyphicon glyphicon glyphicon-random glyphicon_product_css_compare" ></span>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock content_block %}

{% block js_block %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'bookncart_web/bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bookncart_web/slick/slick.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bookncart_web/js/modernizr.js' %}"></script>

<script type="text/javascript" src="{% static 'bookncart_web/parallax/parallax.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bookncart_web/subpages/js/js_with_slick_without_parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'bookncart_web/bootstrap_rating_bar/star-rating.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bookncart_web/subpages/product/js/addToCartQuantityBox.js' %}"></script>

<script type="text/javascript">
	$("#write_review_line").click(function () {
		$("#write_new_review_div").toggle("slow");
	});
</script>
{% endblock js_block %}
</body>
</html>